# permissions for end users to view mailgunmachines.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: mailgunmachine-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: cluster-api-provider-mailgun
    app.kubernetes.io/part-of: cluster-api-provider-mailgun
    app.kubernetes.io/managed-by: kustomize
  name: mailgunmachine-viewer-role
rules:
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - mailgunmachines
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - mailgunmachines/status
  verbs:
  - get
